 --Q1> WRITE A PROCEDURE THAT WILL TAKE ID AS DEPTNO AND GIVE ALL EMPLOYEES DETAILS WHO ARE WORKING IN THAT DEPARTMENT AS REF_CURSOR ?
 --ANS::
 --THE REQUIREMENT IS TO GET ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING THE SAME DEPRATMENT AND TO PRINT THAT IN THE REQUIRED FORMAT.
--HERE I AM CREATING A PROCEDURE THAT WILL TAKE ID AS IN PARAMETER AND SYS_REFCURSOR AS OUT PARAMETER .
CREATE  OR REPLACE PROCEDURE PROC_GET(
                                       ID IN EMP.DEPTNO%TYPE
                                      ,DETAILS OUT SYS_REFCURSOR
                                     )
 IS 
  BEGIN 
    OPEN DETAILS FOR 
    SELECT * FROM EMP
    WHERE DEPTNO= ID ;
    
  END;
  
--HERE I AM CALLING THE PROCEDURE IN A PL/SQL BLOCK TO GET THE DETAILS FROM EMP TABLE 
DECLARE 
DETAILS   SYS_REFCURSOR; --THIS REF CURSOR WILL GIVE THE OUTPUT FROM THE PROCEDURE 
EMP_DET EMP%ROWTYPE;	  --THIS VARIABLE WILL STORE THE DETAILS AND PROCESS FOR THE OUTPUT IN DBMS_OUTPUT FILE 
VID NUMBER := '&ID';	 --THIS WILL ASK THE ID DETAILS IN RUN TIME TO THE USER FOR DYNAMIC PURPOSE
BEGIN 
     PROC_GET(VID,DETAILS);
     LOOP
     FETCH DETAILS INTO EMP_DET;
     EXIT WHEN DETAILS%NOTFOUND;
     DBMS_OUTPUT.PUT_LINE(EMP_DET.ENAME||'  '||EMP_DET.DEPTNO||'  '||EMP_DET.JOB||'  '||EMP_DET.SAL||'  '||EMP_DET.HIREDATE);
     END LOOP;
END;

--Thank You for reading this code.